### PR TITLE
Add `openDirection` prop

### LINKED ISSUE #648: Open upwards?
My date picker sits at the bottom of the page. Is it possible to make the calendar open upwards?

### PR DESCRIPTION
**Pull request by timhwang21**
Fixes #648.

* Add `openDirection` prop to `<DateRangePicker/>`, `<SingleDatePicker/>`, `<DateRangePickerInputController/>`, `<DateRangePickerInput/>`, `<SingleDatePickerInput/>`, `<DateInput/>
* Add SCSS variables for input font size, padding, etc. (used in calculation for open-up absolute positioning)
* Add stories and tests for new prop

### CODE REVIEW

**Comment by samdjstevens** [comment]
Is there anything stopping this being merged currently? Would love to see this go in!

**Comment by timhwang21** [comment]
Ah, I'll resolve the merge conflicts when I have a sec, hopefully today or tomorrow.

**Comment by samdjstevens** [comment]
Cheers @timhwang21 @majapw !

**Comment by ASH-khan** [comment]
@majapw - so can we take care of singleDatePicker based on viewport height or width?
so in my case by default i want to open calendar down, and if i am at the bottom of the page want calendar to open Up.

please advise?
thanks

**Pull request merged**
