### PR TITLE
Allow installing with React 17 and 18

### PR DESCRIPTION
**Pull request by me4502**
Currently the peer dependencies are strictly set to React 16 as a maximum. As React 17 has been out for a long time, and React 18 for a little bit, it makes sense to allow this to install alongside more modern React versions

### CODE REVIEW

**Review by ljharb — CHANGES_REQUESTED** [review]
Unfortunately this can't land until we can test on these react versions, and until all of our dependencies support them.

airbnb-prop-types doesn't yet support react > 16, because enzyme doesn't yet support them, which also blocks react-dates from upgrading.

**Comment by me4502** [comment]
Would it be possible to please at least have this published under a tag or something to unblock people who're using rigid build systems like GAE's CloudBuild config?

**Comment by ljharb** [comment]
No. Without the tests, we can't know if it works or not.

**Comment by GuySerfaty** [comment]
Hey any update on that? can we reopen this?

**Comment by ljharb** [comment]
@GuySerfaty no update.

**Comment by mollerjorge** [comment]
Hey @ljharb do you have any updates on this? or an estimated date? 

Thanks!

**Comment by YakyRef** [comment]
Hi @ljharb . Any update ?

**Comment by ljharb** [comment]
If there were updates, they'd be posted. There's no estimated date because I'm one person working for free and don't know when I'll have time to update enzyme.

**Pull request closed without merging**
