### PR TITLE
Add year selection to DatePicker

### PR DESCRIPTION
**Pull request by BenSwennen**
This adds a year picker as requested in https://github.com/airbnb/react-dates/issues/25 and suggested in https://github.com/airbnb/react-dates/pull/558. I copied some logic for comparing months / years from https://github.com/airbnb/react-dates/pull/558 but used a "next" implementation instead of dropdowns. 

This is my first PR to this repo, so please tell me where I can improve

screen shot 2017-08-16 at 12 50 46

### CODE REVIEW

**Comment by jchapelle** [comment]
I have the feeling that the proposition of [secretyouth](https://github.com/airbnb/react-dates/issues/25#issuecomment-307079186) hwas the more efficient and more good looking solution.

**Comment by sontek** [comment]
@BenSwennen I really like the look of this PR!  Lets make this happen.

**Comment by walreyes** [comment]
@BenSwennen Is there any fork where I could use this?

**Comment by nicholasalanbrown** [comment]
Any progress on merging this into `master`? It's preventing me using this library for my use case and this looks pretty solid.

**Comment by shreyass** [comment]
@BenSwennen I want to merge this in my fork since I really need this feature! Can you make this available on your fork?

**Comment by mukuljainx** [comment]
@shreyass you can use `git fetch origin pull/ID/head:BRANCHNAME` where `BRANCHNAME` is the target branch name. Origin should be this repo and ID is PR ID. Then you can merge to your branch.

**Comment by danvoyce** [comment]
🤨

**Pull request closed without merging**
