### PR TITLE
[Fix] `DayPicker`: Fixed month transition in RTL mode

### PR DESCRIPTION
**Pull request by sajidahmed21**
Fixes incorrect transition of months in RTL mode. GitHub Issue #1551

### CODE REVIEW

**Comment by sajidahmed21** [comment]
@majapw This is a pretty simple fix for a somewhat critical issue. Please review this when you get chance. Thanks!

**Comment by ljharb** [comment]
ah, nvm, i get it :-)

**Comment by sajidahmed21** [comment]
@ljharb I just added a total of 8 test cases, which tests this in both LTR and RTL modes. However, the Travis build keeps failing due to the following:

`ERROR: Coverage for functions (67.37%) does not meet global threshold (67.8%)`
`ERROR: Coverage for statements (82.63%) does not meet global threshold (83%)`

I am not very familiar with test coverage tools yet. Do I need to "expose" the new test cases to `nyc` somewhere?

**Comment by ljharb** [comment]
No; the implication is that the changes reduce the overall coverage percentage, and that your new tests aren't enough to clear the thresholds.

**Review by ljharb — APPROVED** [review]

**Pull request merged**
