### PR TITLE
Feature: Add mindate maxdate props to daterangepicker

### PR DESCRIPTION
**Pull request by pedroabreu**
Adding `minDate` and `maxDate` props to the `DateRangePicker` component, to be able to disable navigation in the calendar.

The functionality was only implemented in the `DateRangePickerController`, which is rendered from `DateRangePicker`. This PR just adds the ability to set this props in the main react-dates component

### CODE REVIEW

**Comment by pedroabreu** [comment]
@ljharb added. Can't think of more tests to do, since the logic is already tested in `DateRangePickerController`.

Let me know if anything else needed 👍

**Comment by pedroabreu** [comment]
@ljharb when you have a chance, is there any other test you can think of that's missing ?

**Comment by pedroabreu** [comment]
@ljharb Any more reviews/changes needed ?

**Comment by patrick-lai** [comment]
Suggestion: would make sense to also port this SingleDatePicker.

**Comment by pedroabreu** [comment]
@ljharb @majapw Any change needed here ?

**Comment by AndradeB91** [comment]
Any news on this PR? I really need this merged, please.

**Comment by pedroabreu** [comment]
Same as #1793 and #1794 that has been already merged and part of [21.2.0](https://github.com/airbnb/react-dates/blob/master/CHANGELOG.md#2120)

**Pull request closed without merging**
