### PR TITLE
[Fix] `DateRangePickerInput`: `customArrowIcon` always overrides RTL or small icon

### LINKED ISSUE #1507: Can't change input arrow icon when in RTL view
**react-dates version**
react-dates@18.3.1

**Describe the bug**
When trying to edit the arrow icon inside the input with the prop `customArrowIcon` and the prop `isRTL` is set to `true`, the custom arrow icon isn't used.

**Source code (including props configuration)**
```
<DateRangePicker
  startDate={this.state.startDate}
  startDateId="your_unique_start_date_id"
  endDate={this.state.endDate}
  endDateId="your_unique_end_date_id"
  onDatesChange={({ startDate, endDate }) => this.setState({ startDate, endDate })}
  focusedInput={this.state.focusedInput}
  isRTL={true}
  customArrowIcon={<CalArrowIcon/>}
  onFocusChange={focusedInput => this.setState({ focusedInput })}
/>
```

**Desktop (please complete the following information):**
 - OS: macOS Mojave (10.14.2)
 - Browser: Chrome
 - Version: 71

**Additional context**
I would be glad to submit a PR for this issue as it looks like a minor change.

### PR DESCRIPTION
**Pull request by MatanBobi**
This PR is to enable customArrowIcon when using the calendar in RTL view.
If there is a customArrowIcon it will override the other arrows (small or RTL default arrow).

Fixes #1507 and #1537.

### CODE REVIEW

**Comment by MatanBobi** [comment]
Hi @ljharb, I'll try to free up some time and add a test for this one :)

**Comment by americool** [comment]
Hey looks like this one was abandoned? It would be great if we could get going again or open a new up to date PR as it also addresses this issue. 

https://github.com/airbnb/react-dates/issues/1537

**Comment by MatanBobi** [comment]
Hi @americool, not abandoned, I'll get to it probably next week :)

**Comment by MatanBobi** [comment]
@ljharb @americool 
I've created https://github.com/airbnb/react-dates/pull/2082 so I'm closing this one, thanks! :)

**Comment by ljharb** [comment]
Please don’t open duplicate PRs; now i have to keep both in sync.

**Comment by MatanBobi** [comment]
Sorry @ljharb I've closed this one just to keep the order since I've created a new branch in my fork.. The new PR contains everything from this PR.

**Comment by ljharb** [comment]
I'm not sure what "keep the order" means.

**Comment by MatanBobi** [comment]
> I'm not sure what "keep the order" means.

I just didn't want to push from master so I've created a new pr from a different branch. Sorry for the trouble.

**Review by ljharb — APPROVED** [review]

**Comment by amitmiran137** [comment]
> Please don’t open duplicate PRs; now i have to keep both in sync.

this doesn't seem like an encouraging open-source approach.
this guy invested his free time fixing an annoying bug and instead you complain

**Comment by ljharb** [comment]
@amitmiran137 thanks for your feedback. i assume you’re aware that just because someone invests free time, that such investment can still impose costs on others - like the time i spend reviewing the PR and maintaining packages, which consumes much more free time every month than any PR is likely to.

**Comment by mazenemam19** [comment]
I'm facing this issue again, customArrowIcon is overridden when isRTL is set to true

**Pull request merged**
