### PR TITLE
Export date comparison methods

### PR DESCRIPTION
**Pull request by majapw**
This PR exports the following date comparison methods as utility classes:
```
  isInclusivelyAfterDay
  isInclusivelyBeforeDay
  isNextDay
  isSameDay
```

### CODE REVIEW

**Comment by ljharb** [comment]
Assuming these methods are unit-tested, should we also have a test that verifies the things that `index.js` exports?

**Comment by majapw** [comment]
That is probably a good idea. Can you write a test for this file in the same way we test our components?

**Comment by majapw** [comment]
(also these methods are definitely unit-tested, who are you even talking to @ljharb :P)

**Comment by ljharb** [comment]
We can, but we'd need to do `npm run build` on each test run in order to get the lib components. I can add a commit to your branch if you like?

**Comment by ljharb** [comment]
Actually now that I think about it, that test would literally just be duplicating the imports/requires in the index file, and verifying that they were exported - that probably won't add much value.

**Comment by majapw** [comment]
Okay! If you can think of a good way to do this, I would not mind the
commit on this branch!

**Pull request merged**
