### PR TITLE
Added a readOnly prop to the SingleDatePicker

### PR DESCRIPTION
**Pull request by erin-doyle**
This will allow the DateInput to be set as readOnly (addresses #496).

### CODE REVIEW

**Comment by ljharb** [comment]
This LGTM, but it needs a rebase (to remove the merge commit)

**Comment by erin-doyle** [comment]
Ok, I _think_ I've done the rebase properly.  Let me know if not.

**Comment by majapw** [comment]
I think if we're going to add this to the `SingleDatePicker`, it makes sense to add it to the `DateRangePicker` too, no?

Also, I do think we'll be paying some attention to revamping the inputs in the near future so that will likely help work on the problems this prop is trying to solve.

**Comment by ljharb** [comment]
@erin-doyle no, there's still merge commits in the PR. Assuming `origin` is your fork and `source` is this repo, `git checkout readonly_prop_#496 && git fetch source && git rebase source/master && git push -f origin readonly_prop_#496` should do it assuming there's no conflicts.

**Comment by erin-doyle** [comment]
Ok, I've rebased (sorry about that, I am not too strong with the git-fu yet 😜 ) and added the prop to DateRangePicker.

**Comment by erin-doyle** [comment]
Great, thanks! 😄

**Comment by majapw** [comment]
Woo I'll do a release shortly after I get this one other PR in :)

**Pull request merged**
