### PR TITLE
Fix weird border styling behavior for hover date (#378)

### PR DESCRIPTION
**Pull request by ConAntonakos**
My solution for #378! I'm still noticing this weird curviness to the top-<left|right> border styles. I'm not sure how to solve that.

Let me know what you think. Thanks!

### CODE REVIEW

**Comment by majapw** [comment]
Sorry for taking so long to get to this! I think a problem is that in adding these modifiers (to be fair, this is largely due to the way we use modifiers right now), we're going to take a performance hit. It would be cool if it were possible to do this mostly in CSS. :/ I will investigate it a bit more.

**Comment by ConAntonakos** [comment]
No problem, @majapw! I think I agree with you regarding perf, though I haven't tested it thoroughly. I simply wanted to get this solution out at least since it was the first one that came to mind. I also agree about possibly changing this via styling only. Do you think it's possible with the current `<table> <td>` implementation? Do you think that might have to change? I'd be more than happy to rewrite the PR.

**Comment by majapw** [comment]
This still needs to be addressed, but because tables are hard I'm going to close it for now because I do not believe this is the correct solution.

**Comment by ConAntonakos** [comment]
No worries. Thanks for checking in. I'd be happy to update the PR once a better solution is figured out.

**Pull request closed without merging**
