### PR TITLE
Fix keyboard nav

### PR DESCRIPTION
**Pull request by tannerbyers**

### CODE REVIEW

**Comment by ljharb** [comment]
@tannerbyers since you opened this PR from a fork you don't own, I can't force push to it; can you please add me to your fork?

**Comment by ljharb** [comment]
@tannerbyers id prefer to reuse this PR rather than open a new one, could you restore the branch?

**Comment by tannerbyers** [comment]
@ljharb This PR has changes for our forked repo (changes to the package.json, maintainers.md, etc). I think I need to make a new branch/PR off my own fork with only the accessibility changes in it. Does that sound right?

**Comment by ljharb** [comment]
ah, yes, that would be right.

**Comment by ljharb** [comment]
Unless you first rebased this branch off of the source repo’s default branch?

**Pull request closed without merging**
