### PR TITLE
Fix focus after nav button press

### PR DESCRIPTION
**Pull request by nicoleanater**

### CODE REVIEW

**Comment by ljharb** [comment]
I’m confused about your fork; what’s not accessible about react-dates now?

**Comment by nicoleanater** [comment]
> I’m confused about your fork; what’s not accessible about react-dates now?

Hello! I accidentally opened the PR to the main repo.

Answering your question, there is this PR https://github.com/react-dates/react-dates/pull/1954 that is still open. I created a fork to merge it and use this fix.
I'm facing a problem where the next/prev month buttons lose focus after being pressed via keyboard because the Calendar will focus on the next available date.

**Comment by nicoleanater** [comment]
Also, one note is that this fix is currently only working for the default button usage. If using a custom button via `navPrev` or `navNext` the focus keeps being lost. I'm trying to find some workarounds for that.

**Comment by ljharb** [comment]
If you figure it out, and can post a link to a rebased branch with passing tests on #1954, I'll merge it.

**Pull request closed without merging**
