### PR TITLE
Add dayAriaLabelFormat into more places

### PR DESCRIPTION
**Pull request by koba04**
This PR is a follow-up for #842.
I've added `dayAriaLabelFormat` prop into `DayPickerRangeController` and `DayPickerSingleDateController` to pass the prop to `DayPicker`.

### CODE REVIEW

**Comment by koba04** [comment]
Thanks!

**Comment by erin-doyle** [comment]
Sorry I'm very late to the game on this!  I would think this should also be exposed up through SingleDatePicker and DateRangePicker and noted in the README.  As it is right now it's only usable for those using the Controller versions.

**Comment by majapw** [comment]
@erin-doyle I feel like we ended up doing that in a follow-up somewhere. ... did we not?

**Comment by erin-doyle** [comment]
I'm not seeing it.  I think this PR was the "follow-up" PR to cover exposing this prop up the hierarchy further but I don't think it went far enough.

**Comment by koba04** [comment]
> I would think this should also be exposed up through SingleDatePicker and DateRangePicker and noted in the README.

@erin-doyle I've made a PR for this! #984

**Pull request merged**
