### PR TITLE
[Fix] `DayPicker`: update calendarMonthWeeks if numberOfMonths is changed

### LINKED ISSUE #1394: adjustDayPickerHeight not calculating predictably when setting numberOfMonths prop dynamically
On our project, we're using a grid system that optionally passes us a `screenClass` prop to tell us what breakpoint we're currently in. We're using that breakpoint to pass a `numberOfMonths` prop to the `DayPickerRangeController` to render either two months for desktop or one month for mobile. 

When we're doing this, our function initializes as `sm`, which initially passes `numberOfMonths={1}`. It's changed to `numberOfMonths={2}` shortly after once `window.innerWidth` is captured and the method is run. 

Setting it to 1 on initial load breaks `adjustDayPickerHeight` for a month either 2 or 3 greater than the current one. As it's calculated based off of `calendarMonthWeeks`, which is only set on `componentDidMount` right now, that value becomes stale until it's triggered again.

adjustmonthheightissues
## Possible Fix

Adding a check to `componentDidUpdate` for a variation in `numberOfMonths` and then triggering `setCalendarMonthWeeks` again fixes the issue.

### PR DESCRIPTION
**Pull request by haojonat**
Fixes #1394.

### CODE REVIEW

**Comment by haojonat** [comment]
This is a rebase of this pr:

https://github.com/airbnb/react-dates/pull/1395

**Comment by haojonat** [comment]
@LMulvey @ljharb - any ideas on why the builds are failing?

**Comment by ljharb** [comment]
@haojonat there's no need to close and reopen a PR to "kick" the tests; if they don't pass immediately, and should, then there's a problem with the repo and it's not something that can be fixed by a rerun.

The tests are failing right now due to the release of npm 7.

**Comment by haojonat** [comment]
@ljharb ah gotcha, in that case, should i wait for the tests to get fixed?  or are we comfortable enough to get this overridden and merged?

**Comment by ljharb** [comment]
Please do wait; I’ll rebase this PR once master is passing again.

**Comment by haojonat** [comment]
Sounds good, thanks @ljharb

**Review by ljharb — APPROVED** [review]

**Comment by ljharb** [comment]
It looks like the new tests aren't actually covering the new lines, so the coverage requirement isn't being met.

**Comment by haojonat** [comment]
@ljharb, i think i might have force pushed over one of your changes to run the LEGACY_PEER_DEPENDENCIES or something.  My bad.  Could you repush that?

**Comment by haojonat** [comment]
@ljharb - noticed a case where the bug persists.  will push another commit to address that as well as take another look at the tests

**Comment by ljharb** [comment]
@haojonat sounds great, thanks.

**Comment by ljharb** [comment]
Why do the storybook knobs need to be removed?

**Comment by haojonat** [comment]
@ljharb - it was causing the REACT=15 builds to fail for some reason.  /shrug

**Comment by ljharb** [comment]
found another way to fix that.

**Comment by haocow** [comment]
hi @ljharb, I just wanted to see if you were planning on updating the 21.8.0 release commit or creating a new 21.8.1 release based on latest?

**Comment by ljharb** [comment]
Releases can't ever be updated; they're immutable. This PR alone would constitute a patch release, but I'm not sure when the next release will be, nor what its version number.

**Comment by haocow** [comment]
ah, darn, okay

**Comment by abenitesDC** [comment]
Hi @ljharb, do you know what does releasing a patch (or minor) depends on?

**Pull request merged**
