### PR TITLE
[Fix] DateInput: Address accessibility issues

### PR DESCRIPTION
**Pull request by henten20**

### CODE REVIEW

**Comment by ljharb** [comment]
Why did you duplicate this with #2207?

**Comment by LauRoxx** [comment]
This looks to be an accidental PR that was only meant to be a PR on our forked repo (see https://github.com/Availity/react-dates/pull/13 ). Should be good to close again.

**Comment by ljharb** [comment]
@LauRoxx thanks for following up. is there a reason the changes shouldn't be upstreamed?

**Comment by LauRoxx** [comment]
The last commit wasn't a correct solution to the aria-controls issue and was not accepted on our forked repo.

**Pull request closed without merging**
