### PR TITLE
Stop calendar blinking on DateRangePickerInput focus switch (fixes #1523, #1553) [Merged to latest master] 

### LINKED ISSUE #1523: DateRangePicker blinking after select startDate
Hello, there.
I'm  setting up DateRangePicker, but when I select startDate the calendar blinks. 

screencast-localhost-3000-2019 02 01-11-33-13

Here's my code

```
<DateRangePicker
        startDate={this.state.startDate} 
        startDateId="startDate" 
        endDate={this.state.endDate} 
        endDateId="endDate" 
        onDatesChange={({ startDate, endDate }) => this.setState({startDate, endDate})}
        focusedInput={this.state.focusedInput}
        onFocusChange={focusedInput => this.setState({focusedInput})} 
      />
```

### PR DESCRIPTION
**Pull request by EugeneDraitsev**
This is merged to latest master #1553 PR, because it looks abandoned

### CODE REVIEW

**Comment by ljharb** [comment]
Reopening; I’ll have to keep this in sync with #1553

**Comment by ljharb** [comment]
@EugeneDraitsev please pull the changes from #1553 into your `patch-1` branch; for some reason I'm unable to force push to it to update this PR.

**Comment by ljharb** [comment]
@EugeneDraitsev it'd be great if you restored the branch, reopened the PR, and followed my instructions, to properly close the PR :-/

**Comment by EugeneDraitsev** [comment]
Sure, 1 min

**Comment by ljharb** [comment]
Specifically, force pushing 0d2ab17 to your branch - no merge commit or anything, just `git push origin 0d2ab17:patch-1 -f`

**Comment by EugeneDraitsev** [comment]
0d2ab17 is not in a tree (maybe it was squashed) so I pushed 74447a7 to patch-1 (I hope I will help)

**Comment by ljharb** [comment]
you may have to fetch first; it's definitely in master.

**Comment by ljharb** [comment]
that works tho, thanks

**Pull request closed without merging**
