### PR TITLE
[Fix] `CalendarMonthGrid`: Fix iOS 14 navigation 

### LINKED ISSUE #2034: Can't navigate more then 3 months ahead
I have a problem. I use the airbnb react-dates date picker and I want to be able to navigate 12 months from current date. All the demos and also my date picker can only navigate 3 months from current date with the nextMonth button.

Anyone have a clue what's going on?

### LINKED ISSUE #2050: [IOS 14] When I click the arrow to move for he next month, it only move to the next 3 months! and not after that!
**react-dates version**
e.g. react-dates@18.3.1

**Describe the bug**

**Source code (including props configuration)**
```jsx
<DateRangePicker
  startDate={this.state.startDate}
  startDateId="your_unique_start_date_id"
  endDate={this.state.endDate}
  endDateId="your_unique_end_date_id"
  onDatesChange={({ startDate, endDate }) => this.setState({ startDate, endDate })}
  focusedInput={this.state.focusedInput}
  onFocusChange={focusedInput => this.setState({ focusedInput })}
/>
```

### PR DESCRIPTION
**Pull request by mmarkelov**
Fixes #2034. Fixes #2050.

Just find out that there is some problems with `transition` - adding some delay helped

### CODE REVIEW

**Review by ljharb — COMMENTED** [review]
Is this already observable in tests or existing storybook examples?

**Comment by matejstrasek** [comment]
Would be great to merge this soon, can't use transition in iOS14 at the moment.

**Review by mgm793 — APPROVED** [review]

**Comment by erikt9** [comment]
@ljharb 
> Is this already observable in tests or existing storybook examples?

#2034 has an animated gif showing the problem in react-date's storybook.  I was able to reproduce the behavior shown with iOS / Safari 14.0.1

**Review by Tronicnotes — APPROVED** [review]

**Review by ljharb — APPROVED** [review]

**Comment by BlairOu** [comment]
Is the version that fixes this bug released ? I can’t find it

**Comment by BlairOu** [comment]
I have add these code to fixed this bug, please see below, but I still find some problem that the animation is not smooth enough
`:global(.CalendarMonthGrid__animating) {
    transition: transform 200ms ease-in-out 0.1s!important;
  }`

**Comment by ljharb** [comment]
No, it’s not. You can see that by clicking on the commit hash that closed the PR, and seeing there’s no release tags on it.

**Pull request merged**
