### PR TITLE
Added Fn call when month change

### PR DESCRIPTION
**Pull request by phsantiago**
When I was implementing this component, I missed this function to reflect month transitions in others parts of my state.

### CODE REVIEW

**Comment by majapw** [comment]
I'm confused on why we would need the `onMonthChange` callback when we already have the `onPrevMonthClick` and `onNextMonthClick` methods?

**Comment by phsantiago** [comment]
@majapw with `onPrevMonthClick` and `onNextMonthClick` we need to calculate outside the Calendar component how many months has passed, with sums and subtractions. It's easier has this props telling us in what month we are.

**Comment by phsantiago** [comment]
@ljharb Thank you for the feedback. I've made some tweaks, can you review please?

**Comment by majapw** [comment]
@phsantiago If you look at https://github.com/airbnb/react-dates/blob/master/src/components/DayPickerRangeController.jsx#L521 and https://github.com/airbnb/react-dates/blob/master/src/components/DayPickerRangeController.jsx#L545, we actually do pass the current month back to the props pass through the `DateRangePicker`. Something similar happens for the `SingleDatePicker`.

Are you using the `DayPicker` component directly?

**Comment by phsantiago** [comment]
@majapw Wow sorry, you are sure! I'm using `DayPicker` directly, didn't knew about [those](https://github.com/airbnb/react-dates/blob/master/src/components/DayPickerRangeController.jsx#L521) [lines](https://github.com/airbnb/react-dates/blob/master/src/components/DayPickerRangeController.jsx#L545).

**Comment by majapw** [comment]
@phsantiago unless you are doing something dramatically different from picking a range or picking a single date, I would recommend using one of those directly. :) In any case, I don't think that this is necessarily the right strategy to add this prop.

**Pull request closed without merging**
