### PR TITLE
Make sure modifiers recomputation uses noon instead of midnight.

### LINKED ISSUE #1358: isOutsideRange / isDayBlocked styling has a 1 day gap on refresh while the picker is open
Hello there,

I am refreshing my blocked days (using `isOutsideRange`, but `isDayBlocked` has the same issue) on `focusedInput` change (because I'm using daily availabilities and changeover days), and on refresh, the click handlers are correctly set, but the styles have a 1-day offset.
Closing the picker and reopening it focusing immediately the end date input makes it show up correctly.

react-dates_blocked_day_offset_issue

On this GIF, my change over days forbid departure on Mondays and Tuesdays.
You can notice that Monday the 12th show up free (wrong behavior) but cannot be selected (right behavior).
Also, Wednesday the 14th show up blocked (wrong behavior) but can be selected (right behavior).
I also demonstrate the closing/reopening whigh correctly updates everything.

Here's how I implemented my isOutsideRange method:
```js
  checkPickerOutsideRange = day => {
    const pricingIndex = this.listing.prices.findIndex(p => moment.range(p.startDate, p.endDate).contains(day))

    if (pricingIndex === -1) {
      return true
    }

    const { startDate } = this.listing.prices[pricingIndex]
    const allFutureAvailabilities = this.listing.prices.slice(pricingIndex).map(p => p.availability).join('')
    const allFutureChangeOvers = this.listing.prices.slice(pricingIndex).map(p => p.changeOverDays).join('')
    const currentDayIndex = moment.range(startDate, day).diff('days')

    if (this.state.focusedInput === START_DATE) {
      return allFutureAvailabilities.charAt(currentDayIndex) === 'U' ||
        allFutureChangeOvers.charAt(currentDayIndex) === 'O' ||
        allFutureChangeOvers.charAt(currentDayIndex) === 'X'
    } else if (this.state.focusedInput === END_DATE) {
      const nextBlockedDayOffset = allFutureAvailabilities.indexOf('U', moment.range(startDate, this.props.applicationStore.travelDates.startDate).diff('days'))
      const nextBlockedDay = moment(startDate).add(nextBlockedDayOffset, 'days')
      return day.isBefore(this.props.applicationStore.travelDates.startDate, 'day') ||
        day.isAfter(nextBlockedDay, 'day') ||
        allFutureChangeOvers.charAt(currentDayIndex) === 'I' ||
        allFutureChangeOvers.charAt(currentDayIndex) === 'X'
    }

    // Default is blocked, shouldn't be reached
    return true
  }
```

Have I done anything wrong or is that a bug ?
Thanks !

### PR DESCRIPTION
**Pull request by fmauNeko**
All other moments are set at noon in the components.

Closes #1358.

### CODE REVIEW

**Comment by fmauNeko** [comment]
Hi! Here are some test, I hope I did it the right way.

**Comment by ljharb** [comment]
@fmauNeko thanks - i think it'd be better, instead of testing "sets the time to noon", if the tests tested the actual real-world case that breaks when the time is set wrong.

**Comment by fmauNeko** [comment]
I'm not sure I see how to test that, as the moments are created from inside the component themselves, from the component's state.

**Comment by ljharb** [comment]
I was envisioning using enzyme to construct a component while mocking time to recreate the conditions under which the bug appears.

**Comment by ljharb** [comment]
@fmauNeko looks like you deleted your fork, which is unfortunate; it means this PR can't ever land :-(

**Pull request closed without merging**
