### PR TITLE
Fix typo in DateInput.

### PR DESCRIPTION
**Pull request by codejunkienick**
This typo caused the wrong position of fang when using OPEN_UP constant for openDirection.

### CODE REVIEW

**Comment by codejunkienick** [comment]
@ljharb we can test if svg element has 'bottom' or 'top' key in styles object.

**Comment by ljharb** [comment]
Hmm, true, testing styles is probably the only way to cover it, and testing styles is generally not a good practice.

**Comment by ljharb** [comment]
Let's get the tests passing, and then we can probably go forward as-is.

**Comment by majapw** [comment]
Fixes https://github.com/airbnb/react-dates/issues/904

**Comment by majapw** [comment]
Will merge this if travis ever feels better 🤒

**Pull request merged**
